import React,{useMemo,useState}from"react";
import{Folder,HardDrive,ChevronLeft,ChevronRight,Plus,Trash2,FileText,LayoutGrid,List,Search,RefreshCw}from"lucide-react";
import{children,normalizePath,loadFS,saveFS,mkdir,touch,remove,readFile}from"../system/filesystem.js";
export default function Finder(){
 const[fs,setFs]=useState(loadFS),[path,setPath]=useState("/"),[hist,setHist]=useState(["/"]),[pos,setPos]=useState(0),[view,setView]=useState("icons"),[selected,setSelected]=useState(null),[query,setQuery]=useState(""),[preview,setPreview]=useState("");
 const items=useMemo(()=>children(fs,path).filter(x=>!query||x.name.toLowerCase().includes(query.toLowerCase())),[fs,path,query]);
 const go=p=>{const n=normalizePath(p,path);if(!fs[n]||fs[n].type!=="dir")return;const h=hist.slice(0,pos+1);h.push(n);setHist(h);setPos(h.length-1);setPath(n);setSelected(null);setPreview("")};
 const mutate=fn=>{const n=JSON.parse(JSON.stringify(fs));try{fn(n);saveFS(n);setFs(n)}catch(e){alert(e.message)}};
 const newFolder=()=>{const n=prompt("Folder name");if(n)mutate(x=>mkdir(x,normalizePath(n,path)))};
 const newFile=()=>{const n=prompt("File name");if(n)mutate(x=>touch(x,normalizePath(n,path),"New makOS document\n"))};
 const del=()=>{if(selected)mutate(x=>remove(x,selected));setSelected(null);setPreview("")};
 const open=x=>{if(x.type==="dir")go(x.path);else{setSelected(x.path);try{setPreview(readFile(fs,x.path))}catch{setPreview("")}}};
 return <div className="finder"><aside><div className="finderSection"><b>Favorites</b>{[["Recents","/Users/mako"],["Desktop","/Users/mako/Desktop"],["Documents","/Users/mako/Documents"],["Downloads","/Users/mako/Downloads"],["Applications","/Applications"]].map(([n,p])=><button className={path===p?"sel":""} key={n} onClick={()=>go(p)}><Folder size={16}/>{n}</button>)}</div><div className="finderSection"><b>Locations</b><button className={path==="/"? "sel":""} onClick={()=>go("/")}><HardDrive size={16}/>Macintosh HD</button></div></aside>
 <main className="finderMain"><div className="toolbar"><button onClick={()=>pos&& (setPos(pos-1),setPath(hist[pos-1]))} disabled={!pos}><ChevronLeft/></button><button onClick={()=>pos<hist.length-1&&(setPos(pos+1),setPath(hist[pos+1]))} disabled={pos>=hist.length-1}><ChevronRight/></button><div className="finderPath">{path}</div><div className="finderSearch"><Search size={14}/><input placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>setView(view==="icons"?"list":"icons")}>{view==="icons"?<List/>:<LayoutGrid/>}</button><button onClick={newFolder}><Plus/></button><button onClick={newFile}><FileText/></button><button onClick={()=>{setFs(loadFS());setPreview("")}}><RefreshCw/></button><button onClick={del} disabled={!selected}><Trash2/></button></div>
 <div className={"fileGrid "+(view==="list"?"listView":"")}>{items.map(x=><button className={selected===x.path?"fileSelected":""} key={x.path} onClick={()=>setSelected(x.path)} onDoubleClick={()=>open(x)}>{x.type==="dir"?<IconBox folder/>:<FileText size={34}/>}<span>{x.name}</span></button>)}{!items.length&&<div className="emptyFinder">No items found</div>}</div>
 {selected&&preview!==""&&<div className="finderPreview"><b>{selected.split("/").pop()}</b><pre>{preview}</pre></div>}<div className="finderStatus">{items.length} items · {path}</div></main></div>
}
function IconBox({folder}){return <span style={{fontSize:36}}>{folder?"📁":"📄"}</span>}