import React,{useEffect,useState}from"react";
import{ChevronLeft,ChevronRight,RotateCw,Plus,Globe,Home,Star,X,ExternalLink,Link2}from"lucide-react";
const DUMB_REPO="https://github.com/alexiusandromedavsgalaxia-lgtm/dumbNavigator";
const getBridge=()=>{try{return localStorage.getItem("makOS.dumbNavigatorUrl")||""}catch{return""}};
export default function Safari(){const[tabs,setTabs]=useState([{id:1,title:"Start Page",url:"makos://start"}]),[active,setActive]=useState(1),[history,setHistory]=useState(["makos://start"]),[pos,setPos]=useState(0),[url,setUrl]=useState("makos://start"),[bridge,setBridge]=useState(getBridge());
 const tab=tabs.find(x=>x.id===active)||tabs[0];
 useEffect(()=>{const f=e=>{if(e.data?.type==="dumbNavigator:url"){setUrl(e.data.url)}};window.addEventListener("message",f);return()=>window.removeEventListener("message",f)},[]);
 const nav=u=>{let v=u.trim();if(!v)return;if(v==="dumb://dumbNavigator"||v==="dumb://home")v="makos://start";else if(!v.includes("://"))v="https://www.google.com/search?q="+encodeURIComponent(v);setUrl(v);setTabs(t=>t.map(x=>x.id===active?{...x,url:v,title:v==="makos://start"?"Start Page":v.replace(/^https?:\/\//,"").slice(0,24)}:x));const h=history.slice(0,pos+1);h.push(v);setHistory(h);setPos(h.length-1)};
 const add=()=>{const id=Date.now();setTabs(t=>[...t,{id,title:"Start Page",url:"makos://start"}]);setActive(id);setUrl("makos://start")};const close=id=>{if(tabs.length===1)return;const rest=tabs.filter(x=>x.id!==id);setTabs(rest);if(id===active){setActive(rest[rest.length-1].id);setUrl(rest[rest.length-1].url)}};
 const openBridge=()=>{if(bridge)window.open(bridge,"_blank","noopener,noreferrer");else window.open(DUMB_REPO,"_blank","noopener,noreferrer")};
 return <div className="browser"><div className="browserTabs">{tabs.map(t=><button className={t.id===active?"tab active":"tab"} key={t.id} onClick={()=>{setActive(t.id);setUrl(t.url)}}>{t.title}<X size={13} onClick={e=>{e.stopPropagation();close(t.id)}}/></button>)}<button onClick={add}><Plus/></button></div><div className="browserbar"><button onClick={()=>pos>0&&(setPos(pos-1),setUrl(history[pos-1]))} disabled={!pos}><ChevronLeft/></button><button onClick={()=>pos<history.length-1&&(setPos(pos+1),setUrl(history[pos+1]))} disabled={pos>=history.length-1}><ChevronRight/></button><button onClick={()=>nav("makos://start")}><Home/></button><div className="address"><Globe size={14}/><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&nav(url)}/></div><button onClick={()=>nav(url)}><RotateCw/></button></div><div className="webpage">{url==="makos://start"?<div className="heroGlass"><span>makOS Safari</span><h1>Start Page</h1><p>Safari is wired for dumbNavigator.</p><div className="quickLinks"><button onClick={()=>nav("dumb://dumbNavigator")}><Link2 size={14}/> dumbNavigator</button><button onClick={openBridge}><ExternalLink size={14}/> Open dumbNavigator</button><button onClick={()=>nav(DUMB_REPO)}><Star size={14}/> Source repository</button></div><div className="bridgeBox"><b>dumbNavigator bridge</b><input value={bridge} onChange={e=>{setBridge(e.target.value);try{localStorage.setItem("makOS.dumbNavigatorUrl",e.target.value)}catch{}}} placeholder="URL de dumbNavigator desplegado"/><small>Si dumbNavigator está en otra URL, guárdala aquí. Safari la reutilizará.</small></div></div>:url.startsWith("https://")?<div className="browserExternal"><Globe size={52}/><h2>{url.replace(/^https?:\/\//,"")}</h2><p>La navegación externa se abre fuera del sandbox cuando el sitio no permite incrustación.</p><button onClick={()=>window.open(url,"_blank","noopener,noreferrer")}>Open externally</button></div>:<div className="browserExternal"><Globe size={52}/><h2>{url}</h2><p>Ruta local de makOS.</p><button onClick={openBridge}>Abrir dumbNavigator</button></div>}</div></div>}