import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Apple,Search,Wifi,Volume2,BatteryFull,Folder,Globe,Terminal as TerminalIcon,Settings,CalendarDays,StickyNote,Calculator,Music2,Image as ImageIcon,Trash2,ChevronLeft,ChevronRight,Plus,Minimize2,Maximize2,X,Power,Monitor,Palette,HardDrive,Play,Pause,SkipBack,SkipForward,Grid2X2}from"lucide-react";
import"./styles.css";
import{BOOT_STAGES,BOOT_LABELS}from"./system/boot.js";
import{children,normalizePath,DEFAULT_FS}from"./system/filesystem.js";
import{children,normalizePath,DEFAULT_FS}from"./system/filesystem.js";
const APPS={Finder:[Folder,"linear-gradient(135deg,#70b9ff,#2f72e8)"],Safari:[Globe,"linear-gradient(135deg,#67d5ff,#3574ff)"],Terminal:[TerminalIcon,"linear-gradient(135deg,#242833,#080a0f)"],Settings:[Settings,"linear-gradient(135deg,#8b95a8,#454d5e)"],Calendar:[CalendarDays,"linear-gradient(135deg,#fff,#ff5364)"],Notes:[StickyNote,"linear-gradient(135deg,#fff36a,#ffc400)"],Calculator:[Calculator,"linear-gradient(135deg,#5d6471,#222630)"],Music:[Music2,"linear-gradient(135deg,#ff7cbd,#9b37f2)"],Photos:[ImageIcon,"linear-gradient(135deg,#ffbf5f,#ef4e8a,#684cff)"],Downloads:[Folder,"linear-gradient(135deg,#8ed2ff,#2572d9)"],System:[Monitor,"linear-gradient(135deg,#6b7280,#1f2937)"]};
function Icon({name,size=24}){const[C,bg]=APPS[name]||APPS.Finder;return <span className="appIcon" style={{background:bg}}><C size={size}/></span>}
function useClock(){const[d,setD]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setD(new Date()),1000);return()=>clearInterval(t)},[]);return d}
function App(){const date=useClock(),[boot,setBoot]=useState(true),[windows,setWindows]=useState([]),[active,setActive]=useState(null),[spot,setSpot]=useState(false),[launch,setLaunch]=useState(false),[dark,setDark]=useState(true);useEffect(()=>{const t=setTimeout(()=>setBoot(false),1800);return()=>clearTimeout(t)},[]);if(boot)return <BootScreen/>;const open=a=>{setWindows(w=>w.includes(a)?w:[...w,a]);setActive(a);setLaunch(false)},close=a=>setWindows(w=>w.filter(x=>x!==a)),toggle=a=>windows.includes(a)?setActive(a):open(a);const apps=Object.keys(APPS).filter(x=>x!=="System");return <div className={"os "+(dark?"dark":"light")}><header className="menubar"><div className="menuLeft"><button onClick={()=>open("System")}><Apple size={18} fill="currentColor"/></button><b>makOS</b><span>File</span><span>Edit</span><span>View</span><span>Window</span><span>Help</span></div><div className="menuRight"><button onClick={()=>setSpot(true)}><Search size={16}/></button><Wifi size={16}/><Volume2 size={16}/><BatteryFull size={18}/><span>{date.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"})}</span><b>{date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</b></div></header><main className="desktop"><div className="desktopBrand"><div className="brandOrb">M</div><strong>makOS</strong><small>Tahoe edition</small></div><div className="desktopIcons"><button onDoubleClick={()=>open("Finder")}><Icon name="Finder" size={27}/><span>Macintosh HD</span></button><button onDoubleClick={()=>open("Downloads")}><Icon name="Downloads" size={27}/><span>Downloads</span></button></div>{windows.map((app,i)=><Window key={app} app={app} index={i} active={active===app} onFocus={()=>setActive(app)} onClose={()=>close(app)} dark={dark} setDark={setDark}/>)}</main><Dock apps={apps} windows={windows} active={active} open={toggle} launch={()=>setLaunch(v=>!v)}/>{spot&&<Spotlight apps={apps} onClose={()=>setSpot(false)} open={open}/>} {launch&&<Launchpad apps={apps} open={open} onClose={()=>setLaunch(false)}/>}</div>}
function Window({app,index,active,onFocus,onClose,dark,setDark}){const[max,setMax]=useState(false);return <section className={"window "+(active?"focused ":"")+(max?"maximized":"")} style={max?{}:{left:(7+index*4)+"%",top:(10+index*3)+"%"}} onMouseDown={onFocus}><div className="titlebar"><div className="traffic"><button className="red" onClick={onClose}><X size={10}/></button><button className="yellow" onClick={()=>setMax(false)}><Minimize2 size={9}/></button><button className="green" onClick={()=>setMax(v=>!v)}><Maximize2 size={9}/></button></div><strong>{app}</strong></div><div className="windowBody">{app==="Finder"?<Finder/>:app==="Safari"?<Safari/>:app==="Terminal"?<Terminal/>:app==="Settings"?<SettingsApp dark={dark} setDark={setDark}/>:app==="Calendar"?<Calendar/>:app==="Notes"?<Notes/>:app==="Calculator"?<Calc/>:app==="Music"?<Music/>:app==="Photos"?<Photos/>:<System/>}</div></section>}
function Finder(){const[fs,setFs]=useState(()=>{try{const v=JSON.parse(localStorage.getItem("makOS.fs.v1"));return v&&v["/"]?v:DEFAULT_FS}catch{return DEFAULT_FS}}),[path,setPath]=useState("/"),[history,setHistory]=useState(["/"]),[pos,setPos]=useState(0),[view,setView]=useState("icons"),[selected,setSelected]=useState(null);const items=children(fs,path);const go=p=>{const n=normalizePath(p,path);if(!fs[n]||fs[n].type!=="dir")return;const h=history.slice(0,pos+1);h.push(n);setHistory(h);setPos(h.length-1);setPath(n);setSelected(null)};const refresh=()=>{try{const v=JSON.parse(localStorage.getItem("makOS.fs.v1"));if(v)setFs(v)}catch{}};useEffect(()=>{const t=setInterval(refresh,500);return()=>clearInterval(t)},[]);const back=()=>pos>0&&(setPos(pos-1),setPath(history[pos-1]),setSelected(null));const forward=()=>pos<history.length-1&&(setPos(pos+1),setPath(history[pos+1]),setSelected(null));const newFolder=()=>{const name=prompt("New Folder");if(!name)return;const n={...fs};const p=normalizePath(name,path);if(n[p])return; n[p]={type:"dir"};localStorage.setItem("makOS.fs.v1",JSON.stringify(n));setFs(n)};return <div className="finder"><aside><div className="finderSection"><b>Favorites</b>{[["Recents","/Users/mako"],["Desktop","/Users/mako/Desktop"],["Documents","/Users/mako/Documents"],["Downloads","/Users/mako/Downloads"],["Applications","/Applications"]].map(([n,p])=><button className={path===p?"sel":""} key={n} onClick={()=>go(p)}><Folder size={16}/>{n}</button>)}</div><div className="finderSection"><b>Locations</b><button className={path==="/"?"sel":""} onClick={()=>go("/")}><HardDrive size={16}/>Macintosh HD</button></div></aside><div className="finderMain"><div className="toolbar"><button onClick={back} disabled={pos===0}><ChevronLeft/></button><button onClick={forward} disabled={pos===history.length-1}><ChevronRight/></button><div className="finderPath">{path}</div><button onClick={()=>setView(v=>v==="icons"?"list":"icons")}>{view==="icons"?"☷":"▦"}</button><button onClick={newFolder}><Plus/></button></div><div className={"fileGrid "+(view==="list"?"listView":"")}>{items.map(x=><button className={selected===x.path?"fileSelected":""} key={x.path} onClick={()=>setSelected(x.path)} onDoubleClick={()=>x.type==="dir"&&go(x.path)}><Icon name={x.name.endsWith(".app")?x.name.replace(".app",""):x.type==="dir"?"Finder":"Notes"} size={32}/><span>{x.name}{x.type==="dir"?"":""}</span></button>)}{!items.length&&<div className="emptyFinder">This folder is empty</div>}</div><div className="finderStatus">{items.length} items · {path}</div></div></div>}
function Safari(){const[url,setUrl]=useState("https://www.apple.com");return <div className="browser"><div className="browserbar"><ChevronLeft/><ChevronRight/><div className="address"><Globe size={14}/><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setUrl(e.currentTarget.value)}/></div><Plus/></div><div className="webpage"><div className="heroGlass"><span>makOS browser</span><h1>Welcome to the open web.</h1><p>A lightweight Safari-inspired surface for makOS.</p><button>Open</button></div></div></div>}
function Terminal(){const[lines,setLines]=useState(["Last login: today on makOS","makOS Unix shell 1.0","Type 'help' for commands."]);const[input,setInput]=useState("");const ref=useRef();const run=cmd=>{const c=cmd.trim();if(!c)return;if(c==="clear"){setLines([]);return}let o=c==="help"?"help  ls  pwd  whoami  date  uname  echo  clear  neofetch  apps  open <app>":c==="ls"?"Applications  Desktop  Documents  Downloads  Library  Projects":c==="pwd"?"/Users/mako":c==="whoami"?"mako":c==="uname"?"makOS_Tahoe arm64 Unix":c==="date"?new Date().toString():c==="neofetch"?"M  makOS Tahoe\n   React + Vite / Cloudflare Pages\n   shell: makosh":c==="apps"?Object.keys(APPS).join("  "):c.startsWith("echo ")?c.slice(5):c.startsWith("open ")?("opening "+c.slice(5)+"..."):"zsh: command not found: "+c;setLines(l=>[...l,"$ "+c,o])};return <div className="terminal" onClick={()=>ref.current?.focus()}><div className="termHeader"><span>makOS Unix</span><span>zsh • 1.0</span></div><div className="termLines">{lines.map((l,i)=><div key={i}>{l}</div>)}<div className="prompt"><span>mako@makOS ~ %</span><input ref={ref} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){run(input);setInput("")}}}/></div></div></div>}
function SettingsApp({dark,setDark}){const[tab,setTab]=useState("Appearance");return <div className="settings"><aside>{["Appearance","Desktop & Dock","Network","Keyboard","Privacy","About"].map(x=><button className={tab===x?"sel":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><div className="settingsMain"><h2>{tab}</h2>{tab==="Appearance"&&<><div className="settingCard"><Palette/><div><b>Theme</b><p>Choose how makOS looks.</p></div><button onClick={()=>setDark(v=>!v)}>{dark?"Dark":"Light"}</button></div><div className="settingCard"><Monitor/><div><b>Glass surfaces</b><p>Layered translucent panels.</p></div></div></>}{tab==="About"&&<div className="about"><div className="bigM">M</div><h1>makOS Tahoe</h1><p>Version 1.0 • React + Vite</p></div>}{tab!=="Appearance"&&tab!=="About"&&<div className="placeholder">Preference pane ready for expansion.</div>}</div></div>}
function Calendar(){return <div className="calendar"><h1>{new Date().toLocaleString([],{month:"long",year:"numeric"})}</h1><div className="week">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><b key={x}>{x}</b>)}{Array.from({length:35},(_,i)=><span key={i}>{i<2?"":((i-1)%31)+1}</span>)}</div></div>}
function Notes(){const[text,setText]=useState("Welcome to makOS Notes\n\nThis is a local note.");return <div className="notes"><aside><button className="sel">Quick Note</button><button><Plus size={16}/>New Note</button></aside><textarea value={text} onChange={e=>setText(e.target.value)}/></div>}
function Calc(){const[v,setV]=useState("");const p=x=>{if(x==="="){try{setV(String(Function("return "+v.replaceAll("×","*").replaceAll("÷","/"))()))}catch{setV("Error")}}else if(x==="C")setV("");else setV(s=>s+x)};return <div className="calc"><div className="calcDisplay">{v||"0"}</div><div className="keys">{["C","(",")","÷","7","8","9","×","4","5","6","-","1","2","3","+","0",".","="].map(x=><button onClick={()=>p(x)} key={x}>{x}</button>)}</div></div>}
function Music(){const[play,setPlay]=useState(false);return <div className="music"><div className="album"><Music2 size={70}/></div><h1>makOS Radio</h1><p>Custom desktop soundtrack</p><div className="player"><SkipBack/><button className="play" onClick={()=>setPlay(v=>!v)}>{play?<Pause/>:<Play/>}</button><SkipForward/></div></div>}
function Photos(){return <div className="photos"><div className="photoHero"><ImageIcon size={80}/><h1>Photo Library</h1><p>Your visual workspace.</p></div><div className="photoGrid">{["Aurora","Glass","Ocean","Sunset","City","Mountain"].map(x=><div key={x}>{x}</div>)}</div></div>}
function System(){return <div className="system"><Power size={54}/><h1>makOS Tahoe</h1><p>Web edition</p></div>}
function Dock({apps,windows,active,open,launch}){return <nav className="dock">{apps.map(x=><button key={x} className={active===x?"dockActive":""} onClick={()=>open(x)} title={x}><Icon name={x} size={25}/>{windows.includes(x)&&<i/>}</button>)}<span className="dockSep"/><button onClick={launch}><Grid2X2 size={25}/></button><button><Trash2 size={25}/></button></nav>}
function Spotlight({apps,onClose,open}){const[q,setQ]=useState("");return <div className="overlay" onClick={onClose}><div className="spotlight" onClick={e=>e.stopPropagation()}><div className="spotInput"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search makOS"/></div>{apps.filter(x=>x.toLowerCase().includes(q.toLowerCase())).map(x=><button key={x} onClick={()=>{open(x);onClose()}}><Icon name={x} size={24}/><span>{x}</span></button>)}</div></div>}
function Launchpad({apps,open,onClose}){return <div className="overlay launchOverlay" onClick={onClose}><div className="launchpad" onClick={e=>e.stopPropagation()}><div className="launchGrid">{apps.map(x=><button key={x} onClick={()=>{open(x);onClose()}}><Icon name={x} size={42}/><b>{x}</b></button>)}</div></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
function BootScreen(){const[stage,setStage]=useState(0);useEffect(()=>{const t=setInterval(()=>setStage(s=>Math.min(s+1,BOOT_STAGES.length-1)),360);return()=>clearInterval(t)},[]);return <div className="bootScreen"><div className="bootLogo">M</div><h1>makOS</h1><p>{BOOT_LABELS[BOOT_STAGES[stage]]}</p><div className="bootTrack"><i style={{width:((stage+1)/BOOT_STAGES.length)*100+"%"}}/></div><small>{BOOT_STAGES[stage]} • {stage+1}/{BOOT_STAGES.length}</small></div>}
