import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Apple,Search,Wifi,Volume2,BatteryFull,Folder,HardDrive,Trash2,Grid2X2,Settings,Globe,Terminal as TerminalIcon,Plus,Monitor,CalendarDays,StickyNote,Music2,Image as ImageIcon,Calculator,ChevronLeft,ChevronRight,Minimize2,Maximize2,X,Wrench}from"lucide-react";
import"./styles.css";
import Finder from"./apps/Finder.jsx";import Safari from"./apps/Safari.jsx";import Terminal from"./apps/Terminal.jsx";import SettingsApp from"./apps/Settings.jsx";import Calendar from"./apps/Calendar.jsx";import Notes from"./apps/Notes.jsx";import Calc from"./apps/Calculator.jsx";import Music from"./apps/Music.jsx";import Photos from"./apps/Photos.jsx";import System from"./apps/System.jsx";import PartsService from"./apps/PartsService.jsx";import{APPS,Icon}from"./apps/catalog.js";import{BOOT_STAGES,BOOT_LABELS}from"./system/boot.js";

function useClock(){const[d,setD]=useState(new Date());useEffect(()=>{const t=setInterval(()=>setD(new Date()),1000);return()=>clearInterval(t)},[]);return d}
function App(){
 const date=useClock(),[boot,setBoot]=useState(true),[windows,setWindows]=useState([]),[active,setActive]=useState(null),[spot,setSpot]=useState(false),[launch,setLaunch]=useState(false),[dark,setDark]=useState(true),[context,setContext]=useState(null),[menu,setMenu]=useState(null),[finderPath,setFinderPath]=useState("/");
 useEffect(()=>{const t=setTimeout(()=>setBoot(false),1800);return()=>clearTimeout(t)},[]);
 useEffect(()=>{const close=()=>setContext(null);window.addEventListener("click",close);return()=>window.removeEventListener("click",close)},[]);
 if(boot)return <BootScreen/>;
 const open=a=>{setWindows(w=>w.includes(a)?w:[...w,a]);setActive(a);setLaunch(false);setContext(null);setMenu(null)};
 const close=a=>setWindows(w=>w.filter(x=>x!==a));
 const toggle=a=>windows.includes(a)?setActive(a):open(a);
 const apps=Object.keys(APPS).filter(x=>x!=="System");
 const desktop=[["Macintosh HD","Finder",HardDrive],["Applications","Finder",Folder],["Downloads","Finder",Folder],["dumbNavigator","Safari",Globe],["Parts & Service","PartsService",Wrench]];
 return <div className={"os "+(dark?"dark":"light")} onContextMenu={e=>{e.preventDefault();setContext({x:e.clientX,y:e.clientY})}}>
  <header className="menubar"><div className="menuLeft"><button onClick={e=>{e.stopPropagation();setMenu(menu==="apple"?null:"apple")}}><Apple size={18} fill="currentColor"/></button><button className="menuTitle" onClick={e=>{e.stopPropagation();setMenu(menu==="mako"?null:"mako")}}>makOS</button><button onClick={e=>{e.stopPropagation();setMenu(menu==="file"?null:"file")}}>File</button><button onClick={e=>{e.stopPropagation();setMenu(menu==="edit"?null:"edit")}}>Edit</button><button onClick={e=>{e.stopPropagation();setMenu(menu==="view"?null:"view")}}>View</button><button onClick={e=>{e.stopPropagation();setMenu(menu==="window"?null:"window")}}>Window</button><button onClick={e=>{e.stopPropagation();setMenu(menu==="help"?null:"help")}}>Help</button></div><div className="menuRight"><button onClick={()=>setSpot(true)}><Search size={16}/></button><Wifi size={16}/><Volume2 size={16}/><BatteryFull size={18}/><span>{date.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"})}</span><b>{date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</b></div></header>
  {menu&&<MenuBarMenu type={menu} close={()=>setMenu(null)} open={open} windows={windows} active={active} dark={dark} setDark={setDark}/>}\n  <main className="desktop" onDoubleClick={()=>setContext(null)}>
   <div className="desktopGlow"/><div className="desktopBrand"><div className="brandOrb">M</div><strong>makOS</strong><small>Tahoe edition</small></div>
   <div className="desktopIcons">{desktop.map(([label,app,I])=><button key={label} onDoubleClick={()=>open(app)}><span className="desktopFileIcon"><I size={29}/></span><span>{label}</span></button>)}</div>
   <div className="desktopWidgets"><div><b>{date.toLocaleDateString([],{weekday:"long"})}</b><strong>{date.getDate()}</strong><span>{date.toLocaleDateString([],{month:"long",year:"numeric"})}</span></div><div><span>makOS</span><b>Everything is ready.</b><small>Local apps · makFS · makKernel</small></div></div>
   {windows.map((app,i)=><Window key={app} app={app} index={i} active={active===app} onFocus={()=>setActive(app)} onClose={()=>close(app)} dark={dark} setDark={setDark}/>)}
  </main>
  {context&&<div className="desktopContext" style={{left:context.x,top:context.y}} onClick={e=>e.stopPropagation()}><button onClick={()=>open("Finder")}>New Finder window</button><button onClick={()=>setSpot(true)}>Search with Spotlight</button><button onClick={()=>open("Settings")}>Desktop Settings</button><button onClick={()=>location.reload()}>Refresh Desktop</button></div>}
  <Dock apps={apps} windows={windows} active={active} open={toggle} launch={()=>setLaunch(v=>!v)} trash={()=>open("Finder")}/>
  {spot&&<Spotlight apps={apps} onClose={()=>setSpot(false)} open={open}/>}
  {launch&&<Launchpad apps={apps} open={open} onClose={()=>setLaunch(false)}/>}
 </div>
}
function MenuBarMenu({type,close,open,windows,active,dark,setDark}){const items={apple:[["About This Mac",()=>open("System")],["System Settings…",()=>open("Settings")],["Sleep",()=>close()],["Restart…",()=>location.reload()],["Shut Down…",()=>close()]],mako:[["About makOS",()=>open("System")],["System Settings…",()=>open("Settings")]],file:[["New Finder Window",()=>open("Finder")],["Open…",()=>open("Finder")],["Close Window",()=>active&&close()]],edit:[["Undo",()=>{}],["Cut",()=>{}],["Copy",()=>{}],["Paste",()=>{}]],view:[["Show All Windows",()=>windows.forEach(open)],["Enter Full Screen",()=>{}]],window:[["Minimize",()=>{}],["Bring All to Front",()=>windows.forEach(open)]],help:[["makOS Help",()=>open("Safari")],["Parts & Service",()=>open("PartsService")]]};return <div className="topMenu"><div className="topMenuInner">{(items[type]||[]).map(([label,fn])=><button key={label} onClick={()=>{fn();close()}}>{label}<span/></button>)}</div></div>}
function Window({app,index,active,onFocus,onClose,dark,setDark}){const[max,setMax]=useState(false),[min,setMin]=useState(false),[pos,setPos]=useState({x:6+index*3,y:8+index*2}),[size,setSize]=useState({w:920,h:650});const ref=React.useRef(null);const drag=React.useRef(null);const resize=React.useRef(null);const startDrag=e=>{if(max||e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y};window.addEventListener("mousemove",moveDrag);window.addEventListener("mouseup",endDrag)};const moveDrag=e=>{if(!drag.current)return;const dx=(e.clientX-drag.current.x)/window.innerWidth*100,dy=(e.clientY-drag.current.y)/window.innerHeight*100;setPos({x:Math.max(0,Math.min(100-size.w/window.innerWidth*100,drag.current.px+dx)),y:Math.max(3,Math.min(100-size.h/window.innerHeight*100,drag.current.py+dy))})};const endDrag=()=>{drag.current=null;window.removeEventListener("mousemove",moveDrag);window.removeEventListener("mouseup",endDrag)};if(min)return null;return <section ref={ref} className={"window "+(active?"focused ":"")+(max?"maximized":"")} style={max?{}:{left:pos.x+"%",top:pos.y+"%",width:size.w+"px",height:size.h+"px"}} onMouseDown={onFocus}><div className="titlebar" onMouseDown={startDrag}><div className="traffic"><button className="red" onMouseDown={e=>e.stopPropagation()} onClick={onClose}><X size={10}/></button><button className="yellow" onMouseDown={e=>e.stopPropagation()} onClick={()=>setMin(true)}><Minimize2 size={9}/></button><button className="green" onMouseDown={e=>e.stopPropagation()} onClick={()=>setMax(v=>!v)}><Maximize2 size={9}/></button></div><strong>{app}</strong><span/></div><div className="windowBody">{app==="Finder"?<Finder/>:app==="Safari"?<Safari/>:app==="Terminal"?<Terminal/>:app==="Settings"?<SettingsApp dark={dark} setDark={setDark}/>:app==="Calendar"?<Calendar/>:app==="Notes"?<Notes/>:app==="Calculator"?<Calc/>:app==="Music"?<Music/>:app==="Photos"?<Photos/>:app==="PartsService"?<PartsService/>:<System/>}</div></section>}
function Dock({apps,windows,active,open,launch,trash}){return <nav className="dock">{apps.map(x=><button key={x} className={active===x?"dockActive":""} onClick={()=>open(x)} title={x}><Icon name={x} size={25}/>{windows.includes(x)&&<i/>}</button>)}<span className="dockSep"/><button onClick={launch} title="Launchpad"><Grid2X2 size={25}/></button><button onClick={trash} title="Finder"><Trash2 size={25}/></button></nav>}
function Spotlight({apps,onClose,open}){const[q,setQ]=useState("");return <div className="overlay" onClick={onClose}><div className="spotlight" onClick={e=>e.stopPropagation()}><div className="spotInput"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search makOS"/></div>{apps.filter(x=>x.toLowerCase().includes(q.toLowerCase())).map(x=><button key={x} onClick={()=>{open(x);onClose()}}><Icon name={x} size={24}/><span>{x}</span></button>)}</div></div>}
function Launchpad({apps,open,onClose}){return <div className="overlay launchOverlay" onClick={onClose}><div className="launchpad" onClick={e=>e.stopPropagation()}><div className="launchGrid">{apps.map(x=><button key={x} onClick={()=>{open(x);onClose()}}><Icon name={x} size={42}/><b>{x}</b></button>)}</div></div></div>}
function BootScreen(){const[stage,setStage]=useState(0);useEffect(()=>{const t=setInterval(()=>setStage(s=>Math.min(s+1,BOOT_STAGES.length-1)),360);return()=>clearInterval(t)},[]);return <div className="bootScreen"><div className="bootLogo">M</div><h1>makOS</h1><p>{BOOT_LABELS[BOOT_STAGES[stage]]}</p><div className="bootTrack"><i style={{width:((stage+1)/BOOT_STAGES.length)*100+"%"}}/></div><small>{BOOT_STAGES[stage]} · {stage+1}/{BOOT_STAGES.length}</small></div>}
createRoot(document.getElementById("root")).render(<App/>);